VisiDarbi/AdvertisementBundle/Entity/Company.php
<?php
namespace VisiDarbi\AdvertisementBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="VisiDarbi\AdvertisementBundle\EntityRepository\AdvertisementEntityRepository")
 * @ORM\HasLifecycleCallbacks
 * @Gedmo\TranslationEntity(class="VisiDarbi\AdvertisementBundle\Entity\CompanyTranslation")
 */
class Company
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @Gedmo\Slug(fields={"name"}, unique=false)
     * @ORM\Column(type="string")
     */
    private $slug;

     /**
     * @Gedmo\Slug(fields={"name"}, unique=false, style="camel")
     * @ORM\Column(type="string", length=1)
     */
    private $az;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $registration_number;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $name;

    /**
     * @Gedmo\Translatable
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $logo;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $logo_path;

    /**
     * @ORM\OneToOne(targetEntity="VisiDarbi\AdvertisementBundle\Entity\Advertisement", inversedBy="companies")
     * @ORM\JoinColumn(name="advertisement_id", referencedColumnName="id", nullable=false, unique=true, onDelete="CASCADE")
     */
    private $advertisement;


    /**
     * @ORM\OneToMany(
     *   targetEntity="VisiDarbi\AdvertisementBundle\Entity\CompanyTranslation",
     *   mappedBy="object",
     *   cascade={"persist", "remove"}
     * )
     */
    private $translations;

    /**
     * This one is not to store - only for contain value
     * @var integer
     */
    private $advertisementsBySlug;

    public function getAdvertisementsBySlug() {
        return $this->advertisementsBySlug;
    }

    public function setAdvertisementsBySlug($advertisementsBySlug) {
        $this->advertisementsBySlug = $advertisementsBySlug;
        return $this;
    }

        /**
     * Constructor
     */
    public function __construct()
    {
        $this->translations = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Company
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Get registration number
     *
     * @return string
     */
    public function getRegistrationNumber()
    {
        return $this->registration_number;
    }

    /**
     * Set registration number
     *
     * @param string $registration_number
     * @return Company
     */
    public function setRegistrationNumber($registration_number)
    {
        $this->registration_number = $registration_number;

        return $this;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Company
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set logo
     *
     * @param string $logo
     * @return Company
     */
    public function setLogo($logo)
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * Get logo
     *
     * @return string
     */
    public function getLogo()
    {
        return $this->logo;
    }

    /**
     * Set advertisement
     *
     * @param \VisiDarbi\AdvertisementBundle\Entity\Advertisement $advertisement
     * @return Company
     */
    public function setAdvertisement(\VisiDarbi\AdvertisementBundle\Entity\Advertisement $advertisement)
    {
        $this->advertisement = $advertisement;

        return $this;
    }

    /**
     * Get advertisement
     *
     * @return \VisiDarbi\AdvertisementBundle\Entity\Advertisement
     */
    public function getAdvertisement()
    {
        return $this->advertisement;
    }

    public function addTranslation(CompanyTranslation $t)
    {
        if (!$this->translations->contains($t)) {
            $this->translations[] = $t;
            $t->setObject($this);
        }
    }


    /**
     * Remove translations
     *
     * @param \VisiDarbi\AdvertisementBundle\Entity\OfferTranslation $translations
     */
    public function removeTranslation(\VisiDarbi\AdvertisementBundle\Entity\OfferTranslation $translations)
    {
        $this->translations->removeElement($translations);
    }

    /**
     * Get translations
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTranslations()
    {
        return $this->translations;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Company
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set az
     *
     * @param string $az
     * @return Company
     */
    public function setAz($az)
    {
        $this->az = $az;

        return $this;
    }

    /**
     * Get az
     *
     * @return string
     */
    public function getAz()
    {
        return $this->az;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeLogoOnRemove()
    {
        $filename = $this->getFullLogoPath();

        if($this->getLogo() && file_exists($filename)) {
            unlink($filename);
        }
    }

    public function getFullLogoPath(){
        $rootPath = __DIR__.'/../../../../web/';
        $filename = $rootPath . $this->getLogoPath() . '/' . $this->getLogo();
        return $filename;
    }

    public function isLogoFileExists(){
        return file_exists($this->getFullLogoPath());
    }

    public function getLogoPath() {
        return $this->logo_path;
    }

    public function setLogoPath($logoPath) {
        $this->logo_path = $logoPath;
        return $this;
    }



}

VisiDarbi/AdvertisementBundle/Resources/views/HighlightAdvertisement/fast1.html.twig
{% form_theme form 'VisiDarbiAdvertisementBundle:AddAdvertisement:paymentRadio.html.twig' %}
{% trans_default_domain "hl_addadvertisement" %}
{% extends 'VisiDarbiCommonBundle::frontend_base.html.twig' %}
{% block additional_header %}
<section class="grayheader">
    <section class="content basket clearfix">
        {% include 'VisiDarbiAdvertisementBundle:HighlightAdvertisement:header.html.twig' %}
    </section>
</section>
{% endblock %}
{% block body %}
<section id="wrapper" class="no_cols clearfix">
    <section class="content clearfix">
        <section class="body">
            <form id="form" class="form form_3 {%if form.vars.errors%}no_ok{%endif%}"  action="{{ path('visidarbi_advertisement_highlight_fast1') }}" method="post" {{ form_enctype(form) }}>

                <section class="section clearfix">
                    <h3>{{'Requisites'|trans}}</h3>
                    <section class="inputblock clearfix">
                        <label for="{{form.companyName.vars.id}}">{{form.companyName.vars.label|trans({},'messages')}}:<b>*</b></label>
                        <section class="input standart {%if form.companyName.vars.errors%} no_ok{%endif%}" > <!-- add class no_ok -->
                            {{form_widget(form.companyName)}}
                        </section>
                    </section>
                    <section class="inputblock clearfix">
                        <label for="{{form.email.vars.id}}">{{form.email.vars.label|trans({},'messages')}}:<b>*</b></label>
                        <section class="input standart{%if form.email.vars.errors%} no_ok{%endif%}"> <!-- add class no_ok -->
                            {{form_widget(form.email, {'attr':{'onChange': 'checkEmail()'}})}}
                        </section>
                    </section>
                    <section class="inputblock clearfix email-note" id="email_note_text_section">
                        <span id="email_note_text"></span>
                    </section>

                    <section class="inputblock clearfix">
                        <label for="{{form.address.vars.id}}">{{form.address.vars.label|trans({},'messages')}}:<b>*</b></label>
                        <section class="input standart long {%if form.address.vars.errors%} no_ok{%endif%}"> <!-- add class no_ok -->
                            {{form_widget(form.address)}}
                        </section>
                    </section>
                    <section class="inputblock clearfix">
                        <label for="{{form.contactPersonName.vars.id}}">{{form.contactPersonName.vars.label|trans({},'messages')}}:<b>*</b></label>
                        <section class="input standart{%if form.contactPersonName.vars.errors%} no_ok{%endif%}"> <!-- add class no_ok -->
                            {{form_widget(form.contactPersonName)}}
                        </section>
                    </section>
                    <section class="inputblock clearfix">
                        <label for="{{form.vat.vars.id}}">{{form.vat.vars.label|trans({},'messages')}}:<b>*</b></label>
                        <section class="input standart{%if form.vat.vars.errors%} no_ok{%endif%}"> <!-- add class no_ok -->
                            {{form_widget(form.vat)}}
                        </section>
                        <div class="ef-input checkbox"><div class="inn">
                                {{form_widget(form.noVat)}}
                                <label for="{{form.noVat.vars.id}}">{{form.noVat.vars.label|trans({},'messages')}}</label>
                            </div></div>
                    </section>
                    <section class="inputblock clearfix">
                        <label for="{{form.registrationNumber.vars.id}}">{{form.registrationNumber.vars.label|trans({},'messages')}}:<b>*</b></label>
                        <section class="input standart{%if form.registrationNumber.vars.errors%} no_ok{%endif%}"> <!-- add class no_ok -->
                            {{form_widget(form.registrationNumber)}}
                        </section>
                    </section>
                    <section class="inputblock clearfix">
                        <label for="{{form.bankCode.vars.id}}">{{form.bankCode.vars.label|trans({},'messages')}}:<b>*</b></label>
                        <section class="input standart {%if form.bankCode.vars.errors%} no_ok{%endif%}"> <!-- add class no_ok -->
                            {{form_widget(form.bankCode)}}
                        </section>
                    </section>
                    <section class="inputblock clearfix">
                        <label for="{{form.bankAccount.vars.id}}">{{form.bankAccount.vars.label|trans({},'messages')}}:<b>*</b></label>
                        <section class="input standart{%if form.bankAccount.vars.errors%} no_ok{%endif%}"> <!-- add class no_ok -->
                            {{form_widget(form.bankAccount)}}
                        </section>
                    </section>
                </section>

                <section class="section v2 clearfix">
                    <h3>{{'Payment methods'|trans}}</h3>
                    <section class="payment">
                        {{form_widget(form.payment)}}
                    </section>
                </section>
                <section class="section sum clearfix">
                    <h3>{{'Price total'|trans}}</h3>
                    <div>
                        <div>
                            {{'Summa bez PVN'|trans}}: <span id="totalPrice"></span>
                            <span class="eur" id="totalPriceSecond"></span>
                        </div>
                        <div>
                            {{'PVN'|trans}} {{vatValue}}%: <span id="vatTotal"></span>
                            <span class="eur" id="vatTotalSecond"></span>
                        </div>
                        <div>
                            {{'Summa ar PVN'|trans}}: <span id="totalPriceWithVat"></span>
                            <span class="eur" id="totalPriceWithVatSecond"></span>
                        </div>
                    </div> 
                    
                </section>
                <section class="bttn v2 clearfix">
                    <section class="accept_field">
                        <div class="ef-input checkbox {%if form.termsAndConditions.vars.errors%} no_ok{%endif%}"><div class="inn">
                                {{form_widget(form.termsAndConditions)}}
                                <label for="{{form.termsAndConditions.vars.id}}">{{form.termsAndConditions.vars.label|trans({},'messages')}}</label>
                            </div></div>
                        <a href="{{path('document', {'slug':'lietosanas-noteikumi'|trans})}}" title="title">{{'Terms and conditions'|trans}}</a>
                        <span>{{'I agree with - text2'|trans}}</span>
                    </section>
                        
 
                    {% for field in form%}
                        {% for error in field.vars.errors%}
                        <div class="no_ok">{{error.getMessage|trans}}</div>
                        {% endfor %}
                    {% endfor %} 
  
                        
                    <a class="orangebutton css3" href="javascript: $('#form').submit()" title="{{'Pay now'|trans}}" tabindex="18"><span title="{{'Pay now'|trans}}">{{'Pay now'|trans}}</span></a>
                </section>
                     {{form_widget(form.priceFirstPage, { 'attr': {'class': "firstpagePrice"}})}}
                     {{form_widget(form.advertisementHlPrice, { 'attr': {'class': "advertisementHlPrice",}})}}
                     {{form_row(form._token)}}
            </form>
        </section>
    </section>
</section>
{% endblock %}

{% block afterfooter %}
<section id="hint" class="hint css3"><section class="txt"></section></section>

{#<script src="{{ asset('bundles/visidarbicommon/js/jquery.min.v1.7.2.js')}}"></script>#}
<script src="{{ asset('bundles/visidarbicommon/js/jquery.autosize.js')}}"></script>
<script src="{{ asset('bundles/visidarbicommon/js/jquery-ui-1.10.3.custom.min.js')}}"></script>
<script src="{{ asset('bundles/visidarbicommon/js/js.js')}}"></script>

<script type="text/javascript"> 

    countPrice();

    function countPrice(){

        {% if secondCurrency %}
            $('#totalPriceSecond').text('({{finalPriceSecond}} {{secondCurrencySign}})');  
            $('#totalPriceWithVatSecond').text('({{finalPriceWithVatSecond}} {{secondCurrencySign}})');
            $('#vatTotalSecond').text('({{vatTotalSecond}} {{secondCurrencySign}})');
        {% endif %}
                    
                    
        $('#vatTotal').text('{{vatTotal}} {{currency}}')
        $('#totalPrice').text('{{finalPrice}} {{currency}}');  
        $('#totalPriceWithVat').text('{{finalPriceWithVat}} {{currency}}');
            
    }      

</script>

{% endblock %}

VisiDarbi/AdvertisementBundle/Resources/views/HighlightAdvertisement/fast2.html.twig
{% trans_default_domain "hl_addadvertisement" %}
{% extends 'VisiDarbiCommonBundle::frontend_base.html.twig' %}
{% block additional_header %}
<section class="grayheader">
    <section class="content basket clearfix">
        {% include 'VisiDarbiAdvertisementBundle:HighlightAdvertisement:header.html.twig' %}
    </section>
</section>
{% endblock %}
{% block body %}
<section id="wrapper" class="no_cols clearfix">
    <section class="content clearfix">
        <section class="body">
                <form class="form form_3 laststep" action="#"> <!-- add class no_ok -->

                {# Accepted payment #}
                {% if paymentStatus == 20 %}
                    <section class="ok_msg_box">
                            <h2>{{'Jūsu sludinājums/-i tika veiksmīgi izcelts/-i'|trans}}</h2>
                    </section> 
                {# Rejected payment #}
                {% elseif advertisement and paymentStatus == 30 %}
                    <section class="ok_msg_box">
                            <h2>{{'Maksājumu sistēma nav apstiprinājusi veikto maksājumu.'|trans}}</h2>
                    </section> 
                {# Pending payment #}
                {% elseif paymentStatus == 10 %}
                    <section class="ok_msg_box">
                            <h2>{{'Jūsu sludinājums/-i tiks izcelts/-i, tiklīdz mēs saņemsim apstiprinājumu no maksājumu sistēmas.'|trans}}</h2>
                    </section>                 
                {% endif %}

                <section class="bttn v2 clearfix">
                        <a class="orangebutton css3" href="{{path('my_advertisments')}}" title="{{'Return to my profile page'|trans}}" tabindex="18"><span title="{{'Return to my profile page'|trans}}">{{'Return to  my profile page'|trans}}</span></a>
                </section>                
                
                </form>
        </section>
    </section>
</section>
{% endblock %}

{% block afterfooter %}

<script src="{{ asset('bundles/visidarbicommon/js/jquery.autosize.js')}}"></script>
<script src="{{ asset('bundles/visidarbicommon/js/js.js')}}"></script>

{% endblock %}

VisiDarbi/AdvertisementBundle/Resources/views/HighlightAdvertisement/header.html.twig
{% trans_default_domain "hl_addadvertisement" %}
<section class="steps">
    {% for i in 1..3%}
        <section class="{% if i<=step %}sel{% endif %} css3" title="{{i}}"><span>{{i}}</span></section>
        {% if i<3 %}<div {% if i<(step) %} class="sel"{% endif %}><span class="css3"></span><span class="css3"></span><span class="css3"></span></div>{% endif %}
    {% endfor %}
</section>

<h1>{{'Highlight advertisement'|trans}}</h1>

VisiDarbi/AdvertisementBundle/Resources/views/HighlightAdvertisement/step3.html.twig
{% trans_default_domain "hl_addadvertisement" %}
{% extends 'VisiDarbiCommonBundle::frontend_base.html.twig' %}
{% block additional_header %}
<section class="grayheader">
    <section class="content basket clearfix">
        {% include 'VisiDarbiAdvertisementBundle:HighlightAdvertisement:header.html.twig' %}
    </section>
</section>
{% endblock %}
{% block body %}
<section id="wrapper" class="no_cols clearfix">
    <section class="content clearfix">
        <section class="body">
                <form class="form form_3 laststep" action="#"> <!-- add class no_ok -->

                {# Accepted payment #}
                {% if advertisement and paymentStatus == 20 %}
                    <section class="ok_msg_box">
                            <h2>{{'Jūsu sludinājums tika veiksmīgi izcelts'|trans}}</h2>
                            <section><a href="{{path('visidarbi_advertisement_show', {'advertisementId': advertisement.getSlugOrPublicId(app.request.attributes.get('_locale'))   })}}" title="title">{{'Apskatīt sludinājumu'|trans}}</a></section>
                    </section> 
                {# Rejected payment #}
                {% elseif advertisement and paymentStatus == 30 %}
                    <section class="ok_msg_box">
                            <h2>{{'Maksājumu sistēma nav apstiprinājusi veikto maksājumu.'|trans}}</h2>
                    </section> 
                {# Pending payment #}
                {% elseif advertisement and paymentStatus == 10 %}
                    <section class="ok_msg_box">
                            <h2>{{'Jūsu sludinājums tiks izcelts, tiklīdz mēs saņemsim apstiprinājumu no maksājumu sistēmas.'|trans}}</h2>
                    </section>                 
                {% endif %}

                <section class="bttn v2 clearfix">
                        <a class="orangebutton css3" href="{{path('visidarbi_advertisement_list')}}" title="{{'Return to advertisements list'|trans}}" tabindex="18"><span title="{{'Return to advertisements list'|trans}}">{{'Return to advertisements list'|trans}}</span></a>
                </section>                
                
                </form>
        </section>
    </section>
</section>
{% endblock %}

{% block afterfooter %}

<script src="{{ asset('bundles/visidarbicommon/js/jquery.autosize.js')}}"></script>
<script src="{{ asset('bundles/visidarbicommon/js/js.js')}}"></script>

{% endblock %}