VisiDarbi/AdvertisementBundle/Entity/AdvertisementType.php
<?php
namespace VisiDarbi\AdvertisementBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/** 
 * @ORM\Entity(repositoryClass="VisiDarbi\AdvertisementBundle\EntityRepository\AdvertisementEntityRepository")
 * @Gedmo\TranslationEntity(class="VisiDarbi\AdvertisementBundle\Entity\AdvertisementTypeTranslation")
 */
class AdvertisementType
{
    
    const TYPE_LIMITED_7_DAY = 10;
    const TYPE_LIMITED_14_DAY = 20;
    const TYPE_UNLIMITED_7_DAY = 30;
    const TYPE_UNLIMITED_14_DAY = 40;
    
    /** 
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    private $id;

    /** 
     * @Gedmo\Translatable 
     * @ORM\Column(type="string", nullable=false)
     */
    private $name;

    /** 
     * @ORM\Column(type="integer", nullable=false)
     */
    private $days_period;

    /** 
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $payd;

    /** 
     * @ORM\Column(type="boolean", nullable=false)
     */
    private $unlimited;    
    
    /** 
     * @ORM\OneToMany(
     *     targetEntity="VisiDarbi\AdvertisementBundle\Entity\AdvertisingTypePrice", 
     *     mappedBy="advertisementType"
     * )
     */
    private $advertisingTypePrices;

    /** 
     * @ORM\OneToMany(targetEntity="VisiDarbi\AdvertisementBundle\Entity\Advertisement", mappedBy="advertisementType")
     */
    private $advertisements;


    /**
     * @ORM\OneToMany(
     *   targetEntity="VisiDarbi\AdvertisementBundle\Entity\AdvertisementTypeTranslation",
     *   mappedBy="object",
     *   cascade={"persist", "remove"}
     * )
     */
    private $translations;

    /** 
     * @ORM\OneToMany(
     *     targetEntity="VisiDarbi\ExternalAdvertisementBundle\Entity\ExternalAdvertisement", 
     *     mappedBy="advertisementType"
     * )
     */
    private $externalAdvertisements;    
    
    
    
    /** 
     * @ORM\OneToMany(targetEntity="VisiDarbi\AdvertisementBundle\Entity\PaidPeriod", mappedBy="advertisementType")
     */
    private $paidPeriod;    
    
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->translations = new ArrayCollection();
        $this->advertisingTypePrices = new \Doctrine\Common\Collections\ArrayCollection();
        $this->advertisements = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Set id
     *
     * @param integer $id
     * @return AdvertisementType
     */
    public function setId($id)
    {
        $this->id = $id;
    
        return $this;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return AdvertisementType
     */
    public function setName($name)
    {
        $this->name = $name;
    
        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set days_period
     *
     * @param integer $daysPeriod
     * @return AdvertisementType
     */
    public function setDaysPeriod($daysPeriod)
    {
        $this->days_period = $daysPeriod;
    
        return $this;
    }

    /**
     * Get days_period
     *
     * @return integer 
     */
    public function getDaysPeriod()
    {
        return $this->days_period;
    }

    /**
     * Set payd
     *
     * @param boolean $payd
     * @return AdvertisementType
     */
    public function setPayd($payd)
    {
        $this->payd = $payd;
    
        return $this;
    }

    /**
     * Get payd
     *
     * @return boolean 
     */
    public function getPayd()
    {
        return $this->payd;
    }

    /**
     * Set unlimited
     *
     * @param boolean $unlimited
     * @return AdvertisementType
     */
    public function setUnlimited($unlimited)
    {
        $this->unlimited = $unlimited;
        return $this;
    }
    
    /**
     * Get unlimited
     *
     * @return boolean 
     */
    public function getUnlimited()
    {
        return $this->unlimited;
    }

    /**
     * Add advertisingTypePrices
     *
     * @param \VisiDarbi\AdvertisementBundle\Entity\AdvertisingTypePrice $advertisingTypePrices
     * @return AdvertisementType
     */
    public function addAdvertisingTypePrice(\VisiDarbi\AdvertisementBundle\Entity\AdvertisingTypePrice $advertisingTypePrices)
    {
        $this->advertisingTypePrices[] = $advertisingTypePrices;
    
        return $this;
    }

    /**
     * Remove advertisingTypePrices
     *
     * @param \VisiDarbi\AdvertisementBundle\Entity\AdvertisingTypePrice $advertisingTypePrices
     */
    public function removeAdvertisingTypePrice(\VisiDarbi\AdvertisementBundle\Entity\AdvertisingTypePrice $advertisingTypePrices)
    {
        $this->advertisingTypePrices->removeElement($advertisingTypePrices);
    }

    /**
     * Get advertisingTypePrices
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getAdvertisingTypePrices()
    {
        return $this->advertisingTypePrices;
    }

    /**
     * Add advertisements
     *
     * @param \VisiDarbi\AdvertisementBundle\Entity\Advertisement $advertisements
     * @return AdvertisementType
     */
    public function addAdvertisement(\VisiDarbi\AdvertisementBundle\Entity\Advertisement $advertisements)
    {
        $this->advertisements[] = $advertisements;
    
        return $this;
    }

    /**
     * Remove advertisements
     *
     * @param \VisiDarbi\AdvertisementBundle\Entity\Advertisement $advertisements
     */
    public function removeAdvertisement(\VisiDarbi\AdvertisementBundle\Entity\Advertisement $advertisements)
    {
        $this->advertisements->removeElement($advertisements);
    }

    /**
     * Get advertisements
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getAdvertisements()
    {
        return $this->advertisements;
    }
    
    public function addTranslation(AdvertisementTypeTranslation $t)
    {
        if (!$this->translations->contains($t)) {
            $this->translations[] = $t;
            $t->setObject($this);
        }
    }    
    

    /**
     * Remove translations
     *
     * @param \VisiDarbi\AdvertisementBundle\Entity\AdvertisementTypeTranslation $translations
     */
    public function removeTranslation(\VisiDarbi\AdvertisementBundle\Entity\AdvertisementTypeTranslation $translations)
    {
        $this->translations->removeElement($translations);
    }

    /**
     * Get translations
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getTranslations()
    {
        return $this->translations;
    }
    
    public function __toString() {
        return (string) $this->getName();
    }

    /**
     * Add externalAdvertisements
     *
     * @param \VisiDarbi\ExternalAdvertisementBundle\Entity\ExternalAdvertisement $externalAdvertisements
     * @return AdvertisementType
     */
    public function addexternalAdvertisement(\VisiDarbi\ExternalAdvertisementBundle\Entity\ExternalAdvertisement $externalAdvertisements)
    {
        $this->externalAdvertisements[] = $externalAdvertisements;
    
        return $this;
    }

    /**
     * Remove externalAdvertisements
     *
     * @param \VisiDarbi\ExternalAdvertisementBundle\Entity\ExternalAdvertisement $externalAdvertisements
     */
    public function removeExternalAdvertisement(\VisiDarbi\ExternalAdvertisementBundle\Entity\ExternalAdvertisement $externalAdvertisements)
    {
        $this->externalAdvertisements->removeElement($externalAdvertisements);
    }

    /**
     * Get externalAdvertisements
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getExternalAdvertisements()
    {
        return $this->externalAdvertisements;
    }

    /**
     * Add paidPeriod
     *
     * @param \VisiDarbi\AdvertisementBundle\Entity\PaidPeriod $paidPeriod
     * @return AdvertisementType
     */
    public function addPaidPeriod(\VisiDarbi\AdvertisementBundle\Entity\PaidPeriod $paidPeriod)
    {
        $this->paidPeriod[] = $paidPeriod;
    
        return $this;
    }

    /**
     * Remove paidPeriod
     *
     * @param \VisiDarbi\AdvertisementBundle\Entity\PaidPeriod $paidPeriod
     */
    public function removePaidPeriod(\VisiDarbi\AdvertisementBundle\Entity\PaidPeriod $paidPeriod)
    {
        $this->paidPeriod->removeElement($paidPeriod);
    }

    /**
     * Get paidPeriod
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getPaidPeriod()
    {
        return $this->paidPeriod;
    }
    
    public function getPrice() 
    {
        return $this->advertisingTypePrices->first();
    }
}

VisiDarbi/AdvertisementBundle/Resources/views/AddAdvertisement/paymentRadio.html.twig
{% trans_default_domain "add_addadvertisement" %}
{% form_theme form _self %}




{% block radio_widget %}
{% set pimages = {

'10':  asset('bundles/visidarbicommon/images/dnb-logo.png'),
'20':  asset('bundles/visidarbicommon/images/nordea-logo.png'),
'30':  asset('bundles/visidarbicommon/images/seb-logo.png'),
'40':  asset('bundles/visidarbicommon/images/swedbank-logo.png'),
'50':  asset('bundles/visidarbicommon/images/paypal-logo.png'),

}%}

{% set pimagesAlt = {

'10':  'dnb',
'20':  'nordea',
'30':  'seb',
'40':  'swedbank',
'50':  'paypal',

}%}

{% spaceless %}
{#{dump(pimages)}#}
{% set altKey = 'payment_bank_alt_' ~ pimagesAlt[value] %}

<div class="ef-input radio {%if value==50 %}v2{%endif%}"><div class="inn">
        <input {{ block('widget_attributes') }} type="radio" {% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} />
        <label for="{{id}}"><img src="{{pimages[value]}}" alt="{{altKey|trans}}" /></label>
</div></div>

{#  <input type="radio" {{ block('widget_attributes') }}{% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} />#}
{% endspaceless %}
{% endblock radio_widget %}


{% block choice_widget_expanded %}
{% spaceless %}
    {% for child in form %}
        {{ form_widget(child) }}
    {% endfor %}
{% endspaceless %}
{% endblock choice_widget_expanded %}

VisiDarbi/AdvertisementBundle/Resources/views/AddAdvertisement/preview_advertisement.html.twig
{% extends 'VisiDarbiAdvertisementBundle:Advertisement:show.html.twig' %}
{% block body %}
<section id="wrapper" class="no_left clearfix">
        <section class="content clearfix">

                <section class="rightcol openwork" data-scrollholder="true">
                        <section data-scrollbox="true">
                                <h3>{{'Contacts'|trans}}:</h3>
                                <div>{{'Contact person'|trans}}: {{advertisement.getContactPerson().getName()}}</div>
                                <div>{{'Position'|trans}}: {{advertisement.getContactPerson().getPosition()}}</div>
                                <div>{{'E-mail'|trans}}: <a href="mailto:{{advertisement.getContactPerson().getEmail()}}" title="title">{{advertisement.getContactPerson().getEmail()}}</a></div>
                                <div>{{'Phone'|trans}}: {{advertisement.getContactPerson().getPhone()}}</div>
                                {% if advertisement.getContactPerson().getFax() %}
                                    <div>{{'Fax'|trans}}: {{advertisement.getContactPerson().getFax()}}</div>
                                {% endif %}
                                {% if advertisement.getContactPerson().getUrl() %}
                                    <div>{{'URL'|trans}}:<a href="{{advertisement.getContactPerson().getUrl()}}"> {{advertisement.getContactPerson().getUrl()}}</a></div>
                                {% endif %}

                                <section class="buttons">
                                        <section class="popup_box"></section>
                                        {% if allowSaveAdvertisement %}
                                        <a class="button css3" title="title" href="javascript: saveFavorite('{{advertisement.publicId}}');"><span id="save_{{advertisement.publicId}}" {%if ( not favorites[advertisement.id] )%}class="save"{% else %}class="saved"{%endif%}>{%if ( not favorites[advertisement.id] )%}{{'Save'|trans}}{% else %}{{'Saved'|trans}}{%endif%}</span></a>
                                        {% endif %}
                                        <a class="button css3 share" id="share_link_{{advertisement.publicId}}" data-href="{{url('visidarbi_advertisement_show', {'advertisementId': advertisement.publicId}, true)}}" data-title="{{advertisement.title}}" data-id="{{advertisement.publicId}}" title="{{'Share'|trans}}" href="#"><span class="share">{{'Share'|trans}}</span></a>
                                        <a class="button css3" title="title" href="javascript: window.print();"><span class="print">{{'Print'|trans}}</span></a>
                                </section>
                        </section>
                </section>



                <section class="body">
                        <section class="opendoc" id="openwork">
                                <section class="company clearfix">
                                        {% if advertisement.getCompany.getLogo and advertisement.getCompany.isLogoFileExists%}
                                        <section class="logo">                                            
                                            <img src="{{  asset(advertisement.getCompany.getLogoPath ~ '/' ~ advertisement.getCompany.getLogo) }}" title="{{advertisement.getCompany.getName}}" alt="{{advertisement.getCompany.getName}}" />
                                        </section>
                                        {% endif %}
                                        <h2>{{advertisement.getCompanies().getName()}}</h2>
                                        <p>{{advertisement.getCompanies().getDescription()}}</p>
                                </section>

                                <p>{{advertisement.getDescription()}}</p>

                                <h1>{{advertisement.getTitle()}}</h1>
                                {% include 'VisiDarbiAdvertisementBundle:Advertisement:show_' ~ advertisement.getFormat|lower ~ '_form.html.twig' ignore missing %}

                                <section class="term">{{'Contest terms'|trans}}: {{'till'|trans}} {{advertisement.getDateTo()|date('d.m.Y.')}}</section>
                                <section class="term" style="padding:0 0 4px 0;">{{advertisement.getCompanies().getName()}}{% if advertisement.getCompanies().getRegistrationNumber() != "" %}, {{'ad.view.company_reg_nr'|trans}}: {{advertisement.getCompanies().getRegistrationNumber()}}{% endif %}</section>
                                <section class="data">{{advertisement.getAdvertisementCountry().name}}{% if advertisement.getAdvertisementCity().name %}, {{advertisement.getAdvertisementCity().name}}{% endif %}<span class="sep"></span>{{'visidarbi.lv'|trans}} - {{advertisement.getPublishedAt|time_ago_in_words}}<span class="sep"></span>{{'ID'|trans}}: {{advertisement.publicId}}<span class="sep"></span>{{'Unique views amount'|trans}}: {{advertisement.getCount()}}</section>                           
                        </section>

                </section>



        </section>
</section>
{% endblock %}

VisiDarbi/AdvertisementBundle/Resources/views/AddAdvertisement/step1.html.twig
{% trans_default_domain "add_addadvertisement" %}
{% extends 'VisiDarbiCommonBundle::frontend_base.html.twig' %}
{% block additional_header %}
<section class="grayheader">
    <section class="content basket clearfix">
{% include 'VisiDarbiAdvertisementBundle:AddAdvertisement:stepheader.html.twig' %}
    </section>
</section>
{% endblock %}
{% block body %}
<section id="wrapper" class="no_cols clearfix">
    <section class="content clearfix">
        <section class="body">
            <section class="choice_type">
<section id="login_hint" class="hint css3"><section class="txt"><div class="close" title="title">{{'Close'|trans}}</div>{{'To use unlimited type...'|trans}} <a href="javascript: auth();" title="title">{{'autorizējaties'|trans}}</a> vai <a href="{{ url('registration') }}" title="title">{{'reģistrējaties'|trans}}</a></section></section>
                
                <section class="txt">{{'Select advertisement type text'|trans}}</section>                
                <section class="list clearfix">
                    {% for item in items%}                     
                        <section {% if item.type.most_popular %}class="most"{% endif %}>
                            <section  {% if item.type.selected %}class="css3"{% endif %}>
                                {% if item.type.most_popular %}<section><span><span class="css3">{{'Most popular'|trans}}</span></span></section>{%endif%}
                                <form id="f{{item.type.id}}" action="{{ path('visidarbi_advertisement_add_step1') }}" method="post" {{ form_enctype(item.form) }} >
                                <h2>{{item.type.description|raw}}</h2>
                                <div>{{item.type.price|raw}} {{currency|raw}}
                                
                                {%if secondCurrency%}
                                ({{item.secondPrice|raw}} {{secondCurrencySign|raw}})
                                {% endif %}
                                
                                </div>
                                
                                {% if user or not item.type.unlimited%}
                                    <a href="javascript: $('#f{{item.type.id}}').submit();" title="{{'Continue'|trans}}" class="orangebutton v2 css3" tabindex="1"><span title="{{'Continue'|trans}}">{{'Continue'|trans}}</span></a>
                                {% elseif item.type.unlimited%}
                                    <!--<a href="javascript: showLoginHint();" title="{{'Continue'|trans}}" class="orangebutton v2 css3" tabindex="1"><span title="{{'Continue'|trans}}">{{'Continue'|trans}}</span></a>-->
																		<a href="#" title="{{'Continue'|trans}}" class="orangebutton v2 css3 auth" tabindex="1"><span title="{{'Continue'|trans}}">{{'Continue'|trans}}</span></a>
                                {% endif %}
                                {{ form_rest(item.form) }}
                                </form>
                            </section>
                        </section>
                    {% endfor %}
                </section>
                
                {% set servicesSlug =  'musu-pakalpojumi'|trans|raw %}
                {% set servicesSlugUrl =  url('document', {'slug': servicesSlug }) %}
                
                <section class="no_tax">{{'Augstākminētās cenas neietver PVN21%'|trans}}</section>
                <section class="txt bottom_info">{{'ad.add.step4.visidarbi_services_info_link: <a href="%info_link_url%">link</a>'|trans({'%info_link_url%': servicesSlugUrl }, 'messages')|raw}}</section>                
                
            </section>
        </section>
    </section>
</section>

{% endblock %}
{% block afterfooter %}
<script type="text/javascript">

function showLoginHint(){
       var hint = $('#login_hint');
        if(!hint.is(':visible')) hint.show();  
        hint.delegate('.close', 'click', function(e){
                hint.hide();
        });        
}

function hideLoginHint(){
        var hint = $('#login_hint');
        if(hint.is(':visible')) hint.hide();
}

function auth(){
    $('#auth_btn').click();
    $("html, body").animate({ scrollTop: 0 }, "slow");
}      


</script>

{%endblock%}

VisiDarbi/AdvertisementBundle/Resources/views/AddAdvertisement/step3_free_form.html.twig
{% trans_default_domain "add_addadvertisement" %}

{%set fieldName = ['content_',l]|join%}
<section class="inputblock css3{%if form[fieldName].vars.errors%} no_ok{%endif%}">
    {{ form_widget(form[fieldName]) }}
</section>
{%if i == 1 %}
<script type="text/javascript">
    function beforeTabMove(tabid, tabs) {
        try {
            for(k in CKEDITOR.instances){
                jQuery('#'+k).val(CKEDITOR.instances[k]);
                var instance = CKEDITOR.instances[k];
                instance.destroy();
                jQuery('#'+k).css('display', 'none');
            }

        } catch(e) {}
    }

    function afterTabMove(tabid, tabs) {
        var editorId = jQuery('[data-tabid='+tabid+'] .content-editor', tabs).attr('id');
        if (typeof(CKEDITOR.instances[editorId]) == 'undefined' || CKEDITOR.instances[editorId]==null) {
            CKEDITOR.replace(editorId, {{ form[fieldName].vars.config | raw }});
        }
    }
</script>
{% endif %}

VisiDarbi/AdvertisementBundle/Resources/views/AddAdvertisement/step3_full_form.html.twig
{% trans_default_domain "add_addadvertisement" %}
<section class="inputblock clearfix">
    {%set fieldName = ['description_',l]|join%}
    <label for="{{form[fieldName].vars.id}}">{{form[fieldName].vars.label|trans({},'messages')}}:{%if i == 1 %}<b>*</b>{%endif%}</label>

    <section class="field">
        <section class="input textarea css3 {%if form[fieldName].vars.errors%} no_ok{%endif%}"> <!-- add class no_ok -->
            {{ form_widget(form[fieldName], { 'attr': {' data-autosize': "true"} })}}
        </section>
    </section>
</section>
<section class="inputblock clearfix">
    {%set fieldName = ['duty_',l]|join%}
    <label for="{{form[fieldName].vars.id}}">{{form[fieldName].vars.label|trans({},'messages')}}:{%if i == 1 %}<b>*</b>{%endif%}<span class="tooltip"></span><span class="tooltip_text">{{'Duties tooltip text'|trans}}</span></label>
    {% set counter=0 %}
    {% for itemField in form[fieldName]%}
        <section class="input standart{%if itemField.vars.errors%} no_ok{%endif%} added"> <!-- add class no_ok -->
            {% if l == defaultLocale %}
                {% set attr = {'data-clone': "true",  'data-index': "1", 'data-nr' : ""~counter~"", 'data-name': 'addadvertisementstep3[duty_' ~l~ ']', 'data-id': 'addadvertisementstep3_duty_'~l~'_'} %}
                <a class="deletethis" href="#" title="title">Remove</a>
            {% else %}
                {% set attr = {'data-index': "1", 'data-nr' : ""~counter~"", 'data-name': 'addadvertisementstep3[duty_' ~l~ ']', 'data-id': 'addadvertisementstep3_duty_'~l~'_'} %}
            {% endif %}
            {{ form_widget(itemField, { 'attr': attr })}}
        </section>
        {% set counter = counter+1 %}
    {% endfor %}
</section>
<section class="inputblock clearfix">
    {%set fieldName = ['requirement_',l]|join%}
    <label for="{{form[fieldName].vars.id}}">{{form[fieldName].vars.label|trans({},'messages')}}:{%if i == 1 %}<b>*</b>{%endif%}<span class="tooltip"></span><span class="tooltip_text">{{'Requirements tooltip text'|trans}}</span></label>
    {% set counter=0 %}
    {% for itemField in form[fieldName]%}
        <section class="input standart{%if itemField.vars.errors%} no_ok{%endif%} added"> <!-- add class no_ok -->
            {% if l == defaultLocale %}
                {% set attr = {'data-index': "2", 'data-nr' : ""~counter~"", 'data-clone': "true", 'data-name': 'addadvertisementstep3[requirement_' ~l~ ']', 'data-id': 'addadvertisementstep3_requirement_'~l~'_'} %}
                <a class="deletethis" href="#" title="title">Remove</a>
            {% else %}
                {% set attr = {'data-index': "2", 'data-nr' : ""~counter~"", 'data-name': 'addadvertisementstep3[requirement_' ~l~ ']', 'data-id': 'addadvertisementstep3_requirement_'~l~'_'} %}
            {% endif %}
            {{ form_widget(itemField, { 'attr': attr })}}
        </section>
        {% set counter = counter+1 %}
    {%endfor%}
</section>
<section class="inputblock clearfix">
    {%set fieldName = ['offer_',l]|join%}
    <label for="{{form[fieldName].vars.id}}">{{form[fieldName].vars.label|trans({},'messages')}}:{%if i == 1 %}<b>*</b>{%endif%}<span class="tooltip"></span><span class="tooltip_text">{{'Offers tooltip text'|trans}}</span></label>
    {% set counter=0 %}
    {% for itemField in form[fieldName]%}
        <section class="input standart{%if itemField.vars.errors%} no_ok{%endif%} added"> <!-- add class no_ok -->

            {% if l == defaultLocale %}
                {% set attr = {'data-index': "3", 'data-nr' : ""~counter~"", 'data-clone': "true", 'data-name': 'addadvertisementstep3[offer_' ~l~ ']', 'data-id': 'addadvertisementstep3_offer_'~l~'_'} %}
                <a class="deletethis" href="#" title="title">Remove</a>
            {% else %}
                {% set attr = {'data-index': "3", 'data-nr' : ""~counter~"", 'data-name': 'addadvertisementstep3[offer_' ~l~ ']', 'data-id': 'addadvertisementstep3_offer_'~l~'_'} %}
            {% endif %}


            {{ form_widget(itemField, { 'attr': attr })}}
        </section>
        {% set counter = counter+1 %}
    {%endfor%}
</section>
<section class="inputblock clearfix">
    {%set fieldName = ['additional_description_',l]|join%}
    <label for="{{form[fieldName].vars.id}}">{{form[fieldName].vars.label|trans({},'messages')}}:{%if i == 1 %}<b>*</b>{%endif%}</label>
    <section class="field">
        <section class="input textarea css3{%if form[fieldName].vars.errors%} no_ok{%endif%}"> <!-- add class no_ok -->
            {{ form_widget(form[fieldName], { 'attr': {' data-autosize': "true"} })}}
        </section>
    </section>
</section>

VisiDarbi/AdvertisementBundle/Resources/views/AddAdvertisement/stepheader.html.twig
{% trans_default_domain "add_addadvertisement" %}
                <section class="steps">
                    {% for i in 1..5%}
                        <section class="{% if i<=step %}sel{% endif %} css3" title="{{i}}"><span>{{i}}</span></section>
                        {% if i<5 %}<div {% if i<(step) %} class="sel"{% endif %}><span class="css3"></span><span class="css3"></span><span class="css3"></span></div>{% endif %}
                    {% endfor %}
                </section>
                
                {% if addPeriod %}
                <h1>{{'Pay now for period and place advertisement in future'|trans}}</h1>
                {% else %}
                <h1>{{'Add advertisement'|trans}}</h1>
                {% endif %}